apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
      annotations:
        cloudwatch.aws.amazon.com/auto-annotate-dotnet: "false"
        cloudwatch.aws.amazon.com/auto-annotate-java: "false"
        cloudwatch.aws.amazon.com/auto-annotate-nodejs: "false"
        cloudwatch.aws.amazon.com/auto-annotate-python: "false"
        instrumentation.opentelemetry.io/inject-dotnet: "false"
        instrumentation.opentelemetry.io/inject-java: "false"
        instrumentation.opentelemetry.io/inject-nodejs: "false"
        instrumentation.opentelemetry.io/inject-python: "false"
    spec:
      containers:
      - name: frontend
        image: 588738610761.dkr.ecr.us-east-2.amazonaws.com/sharanya-group:frontend-latest
        ports:
        - containerPort: 3001
        env:
        - name: REACT_APP_BACKEND_URL
          value: "http://backend-service:3000"
        - name: NODE_ENV
          value: "production"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3001
  type: LoadBalancer
